title: Battery Cooling Project
author: Enrique Lopez Santoyo
email: School:elopezsantoyo@ucmerced.edu Private:Santoyo11Fut@Gmail.com
description: This is where I will be logging all of my work for the Battery Cooling Project
theme: minima 
